//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data;
    using System.Data.SqlClient;

    public partial class BaiHat
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Tài khoản!")]
        [Display(Name = "Mã Bài hát")]
        public string MaBH { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Tài khoản!")]
        [Display(Name = "Tên Bài hát")]
        public string TenBH { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Tài khoản!")]
        [Display(Name = "Tác giả")]
        public string TacGia { get; set; }
    }

    class BaiHatList
    {
        DBConnection db;
        public BaiHatList()
        {
            db = new DBConnection();
        }

        public List<BaiHat> getBaiHat(string id)
        {
            string sql;
            if (string.IsNullOrEmpty(id))
            {
                sql = "Select * from BaiHat";
            }
            else
            {
                sql = "Select * from BaiHat where Id=" + id ;
            }

            List<BaiHat> strList = new List<BaiHat>();
            SqlConnection con = db.getConnection();
            SqlDataAdapter cmd = new SqlDataAdapter(sql, con);
            DataTable dt = new DataTable();

            con.Open();
            cmd.Fill(dt);

            cmd.Dispose();
            con.Close();

            BaiHat strBH;
            for(int i = 0; i < dt.Rows.Count; i++)
            {
                strBH = new BaiHat();

                strBH.Id = Convert.ToInt32(dt.Rows[i]["Id"].ToString());
                strBH.MaBH = dt.Rows[i]["MaBH"].ToString();
                strBH.TenBH = dt.Rows[i]["TenBH"].ToString();
                strBH.TacGia = dt.Rows[i]["TacGia"].ToString();
                strList.Add(strBH);
            }
            return strList;
        }
        public void  ADDBH(BaiHat strBH)
        {
            string sql = "Insert into BaiHat(MaBH,TenBH,TacGia) values(N'"+strBH.MaBH+"',N'"+strBH.TenBH+"',N'"+strBH.TacGia+"')";
            SqlConnection con = db.getConnection();
            SqlCommand cmd = new SqlCommand(sql, con);

            con.Open();
            cmd.ExecuteNonQuery();

            cmd.Dispose();
            con.Close();
        }

        public void EDITBH(BaiHat strBH)
        {
            string sql = "Update BaiHat set MaBH=N'" + strBH.MaBH + "',TenBH=N'" + strBH.TenBH + "',TacGia=N'" + strBH.TacGia + "' where Id='"+strBH.Id+"'";
            SqlConnection con = db.getConnection();
            SqlCommand cmd = new SqlCommand(sql, con);

            con.Open();
            cmd.ExecuteNonQuery();

            cmd.Dispose();
            con.Close();
            
        }
         public void DeleteBH(BaiHat strBH)
        {
            string sql = "Delete from BaiHat where Id="+strBH.Id;
            SqlConnection con = db.getConnection();
            SqlCommand cmd = new SqlCommand(sql, con);

            con.Open();
            cmd.ExecuteNonQuery();

            cmd.Dispose();
            con.Close();
        }
    }
   
}
